language: node_js
node_js:
- '5'
addons:
  code_climate:
    repo_token: 6b9ec3d8db92c21c7e1cfa39ddb46b868793153c83839603dabc5c5ff76aa2ae
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: L7Er66FTx+od7aq0uaZXpI+2El53DrycS/9TL5Abo99F6s7Kxx7R6Y2kndNcvRqK2sO2r3bg2mzmVFD+rkxki5gqIztZUMpI0cUkg7AUXVKw+5AFYSz6CqDwmxtS1azauymr9ScSvcL+4aWvwAPNt0oaZ5UQWfSiENKTlGv1FzCR5m9hanTV6+MHPMYwlSkwC9VUjA+HkrprngCWvjTHtLn8ykdFmS2YkiJP7Y247Kn36fZLI/v65m4iS0cEp0huVzvZXbOlzxtHjDPU9hPYaAS6T7n/14gKZEA1Hy2FLHv+78fPSVCYVS+oAK6mHKHAcq/SOeEsdY9opVM/YDKBxpvUoBv20GQmBd2DTYLmzo/lHFk2g0snAoR2jUrUZYt4DMp/UmmTwZTzCkO2GA90sfFRaGQFv+xKeAQCmPaZOISgmicUvmIxr/FkLNBa+aWSJIld8qepZuiNOLCnFl9yyqnDAs8eFea8gCKaPKiAEgLZAorKcnHSdB3WqF1RuzrhjdnZszjEyO+POWASYwhKk9mMTWuTfR3lcybY9GxfDzsgc2pP37/UWfemfO2gQURgN9TS6/MDxmI1/jZOb+ByOAik99hr4yshu1vssoIZZSWC8FK3RknxfSzEq0j3IShw5a0yrSmjhMMHWEHfRHFvfUwFNmfu0AEuTZwFUXCFo28=
  on:
    tags: true
    branches: true
